# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  # timeout for analysis
  timeout: 5m

linters:
  enable-all: false
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - gosec
    - gocyclo
    - misspell
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US