#!/bin/bash
# Auto-generated script to fix broken documentation links
# Generated by validate-doc-links.go

set -e

# Fixing docs/README.md

# Fixing docs/technical/README.md

# Fixing docs/user-guide/README.md

echo '✅ Link fixes applied!'
echo 'Backup files created with .bak extension'
